matrix:
    include:
        - os: osx
          osx_image: xcode11
          language: objective-c
          env:
              - NAME="Swiftlint"
                RUN_TESTS=False
                USE_XCODE_BUILD=False

        - os: osx
          osx_image: xcode11
          language: objective-c
          env:
              - NAME="SwiftPM"
                RUN_TESTS=True
                USE_XCODE_BUILD=False

#        - os: linux
#          dist: xenial
#          language: c
#          compiler: clang
#          env:
#              - NAME="SwiftPM"
#                RUN_TESTS=True
#                USE_XCODE_BUILD=False
#                DIST="xenial"

#        - os: linux
#          dist: bionic
#          language: c
#          compiler: clang
#          env:
#              - NAME="SwiftPM"
#                RUN_TESTS=True
#                USE_XCODE_BUILD=False
#                DIST="bionic"

script:
  - ./.travis-ci.sh

before_install:
  - ./.travis-ci-before-install.sh
