#if !canImport(ObjectiveC)
import XCTest

extension FinalClassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FinalClassTests = [
        ("testBasicCopy", testBasicCopy),
        ("testIdentities", testIdentities),
        ("testManyCopies", testManyCopies),
        ("testNoCopyIntoCopy", testNoCopyIntoCopy),
        ("testOneCopyOnRead", testOneCopyOnRead),
    ]
}

extension NonFinalClassTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NonFinalClassTests = [
        ("testBasicCopy", testBasicCopy),
        ("testIdentities", testIdentities),
        ("testManyCopies", testManyCopies),
        ("testNoCopyIntoCopy", testNoCopyIntoCopy),
        ("testOneCopyOnRead", testOneCopyOnRead),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FinalClassTests.__allTests__FinalClassTests),
        testCase(NonFinalClassTests.__allTests__NonFinalClassTests),
    ]
}
#endif
